[project]
name = 'stacks-name-registry'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'

[[project.requirements]]
contract_id = 'SM3VDXK3WZZSA84XXFKAFAF15NNZX32CTSG82JFQ4.sbtc-deposit'
[contracts.bitcoin-stamp-v3]
path = 'contracts/bitcoin-stamp-v3.clar'
clarity_version = 3
epoch = 'latest'

[contracts.daily-gm-v3]
path = 'contracts/daily-gm-v3.clar'
clarity_version = 3
epoch = 'latest'

[contracts.stamp-token-v3]
path = 'contracts/stamp-token-v3.clar'
clarity_version = 3
epoch = 'latest'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
